### ISSUE TITLE
Adding support to SRv6 

### ISSUE THREAD

**Issue by zvfvrv** [projectcalico/vpp-dataplane#141]
**Is your feature request related to a problem? Please describe.**
This is not a problem but a new feature: use of a new overlay type in addition to IPinIP and VXLAN, called SRv6 which is based on Segment Routing over IPv6 

**Describe the solution you'd like**
We want to add an additional overlay type called SRv6 in addition to IPinIP and VXLAN.

**Describe alternatives you've considered**
This is a new feature, which is an alternative to IPinIP and VXLAN.

**Additional context**
SRv6 is a networking solution based on RFC [8754](https://tools.ietf.org/html/rfc8754) and on the recent RFC [8986](https://tools.ietf.org/html/rfc8986) (SRv6 Network Programming model).
An overlay based on SRv6 can offer additional features and advantages compared to a traditional IPinIP overlay.

**Comment by AloysAugustin** [comment]
Hi @zvfvrv ! 
Thanks for opening this issue, as discussed offline, we will use gobgp to program VPP with SRv6 routes announced over BGP to achieve this.
In order to do so, we will need to upgrade gobgp (https://github.com/projectcalico/vpp-dataplane/blob/master/go.mod#L35) to a version that supports SRv6 routes, and then update the glue code (https://github.com/projectcalico/vpp-dataplane/blob/master/calico-vpp-agent/routing/bgp_watcher.go#L54) to program the corresponding routes in vpp.

**Comment by zvfvrv** [comment]
Hi @AloysAugustin,
Thanks for your feedback, 
regarding the gobgp upgrade (to latest v2.25.0) can I directly open a PR for that ?

**Comment by AloysAugustin** [comment]
Yes please :)

**Comment by jjgraham** [comment]
Now that https://github.com/projectcalico/vpp-dataplane/pull/186 has merged what is left to do for "Adding support to SRv6 #141" ?

**Comment by sknat** [comment]
Hi @jjgraham @zvfvrv 
I guess we can close this issue now that #186 is merged.
Feel free to re-open another issue if need be.
