### ISSUE TITLE
AF_PACKET interface creation

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#354]
**Environment**
- Calico/VPP version: `latest`
- Kubernetes version: v1.21.1
- kind cluster

**Issue description**
I have a question: why can't I create an `af_packet` interface on the Calico VPP manually? 

**To Reproduce**

1.Go to the Calico VPP container:
`kubectl exec -it -n calico-vpp-dataplane {calico_vpp_pod_name} -c vpp bash`

2.Create a veth pair and UP interfaces:
```
ip link add name vpp1out type veth peer name vpp1host
ip link set dev vpp1out up
ip link set dev vpp1host up
```
3. Run `vppctl` and create `af_packet`:
```
root@kind-worker:~# vppctl
    _______    _        _   _____  ___ 
 __/ __/ _ \  (_)__    | | / / _ \/ _ \
 _/ _// // / / / _ \   | |/ / ___/ ___/
 /_/ /____(_)_/\___/   |___/_/  /_/    

vpp# create host-interface name vpp1host
create host-interface: Invalid interface name

```

Any ideas?

Thank you

**Comment by sknat** [comment]
Hi @glazychev-art 
Sorry for the late reply.
This is due to the fact that VPP runs in its own netns (when its pod is running with `--net=host`). We do this in order to have a netns in which to park the interface when it stays in linux e.g. with AF_PACKET.
When not all uplink interfaces are physical ones, we use the named netns `calico-vpp-ns`, otherwise it's just the netns associated with VPP's pid.

In either cases, if you do 
````
ip link set dev vpp1host netns $(cat /run/vpp/vpp.pid)
````
You should be able to `vpp# create host-interface name vpp1host`

**Comment by sknat** [comment]
Closing this issue, feel free to reopen if this didn't address your usecase
